### ISSUE TITLE
Unexcpected keyword argument

### ISSUE THREAD

**Issue by devtobi** [breuerfelix/instapy-gui#76]
After trying to start the bot via the GUI I get the following error in console:

`__init__() got an unexpected keyword argument 'bypass_suspicious_attempt`

This might be because the argument should no longer be passed to the InstaPy constructor?

**Comment by devtobi** [comment]
I saw that you are already working on that on the feature0.6 branch so you are aware of that problem.

**Comment by breuerfelix** [comment]
@devtobi yeah I was preparing the update to the latest branch but I wasn't able to finish it before my vacation :S I didn't want to push a buggy version to master if I will be off for 2 weeks after :D

i will be back by back programming on next Monday so I will let you know once I merge this :)
